baseURL = "https://wellen.ethz.ch/"
languageCode = "de-ch"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "list"]
defaultContentLanguage = "de"

[params]
    dateFormat = "Jan 2, 2006"

[languages]
    [languages.de]
        title = "Wellen, focusTerra"
        languageName = "de"
        weight = 1


        [languages.de.params]
        weiter = "Weitergedacht"
        weiter_alt = "Weitergedacht Maskottchen für"
        fullscreen_image_alt = "Poster zum Thema"
        description = "Diese Hompage begleitet die Ausstellung, die vom 24. August 2021 bis zum 5. März 2023 an der ETH Zürich gezeigt wird. Dort kannst du die Wellen auf grossen Leuchtbildern entdecken und mit Experimenten selber erforschen. Wir freuen uns auf deinen Besuch!"

        [languages.de.menu]
            [[languages.de.menu.home]]
                name = "Home"
                url = "/"
                weight = 1
            [[languages.de.menu.intros]]
                name = "Tauch ein!"
                url = "/eintauchen"
                weight = 1
            [[languages.de.menu.intros]]
                name = "Wellentypen"
                url = "/wellentypen"
                weight = 2
            [[languages.de.menu.intros]]
                name = "Wellenphysik"
                url = "/wellenphysik"
                weight = 3
            [[languages.de.menu.intros]]
                name = "Mit Wellen durch die Zeit"
                url = "/zeit"
                weight = 4
            [[languages.de.menu.main]]
                name = "Ich sehe was, ..."
                url = "/empfaenger/"
                weight = 1
            [[languages.de.menu.main]]
                name = "Hallo Echo"
                url = "/reflexion/"
                weight = 2
            [[languages.de.menu.main]]
                name = "Achtung-fertig-los"
                url = "/geschwindigkeit/"
                weight = 3
            [[languages.de.menu.main]]
                name = "Energie im Fokus"
                url = "/energie/"
                weight = 4
            [[languages.de.menu.main]]
                name = "Wer suchet, wird finden"
                url = "/lokalisierung/"
                weight = 5
            [[languages.de.menu.main]]
                name = "Daten reisen um die Welt"
                url = "/kommunikation/"
                weight = 6
            [[languages.de.menu.main]]
                name = "Wenn jemand eine Reise tut"
                url = "/veraenderung/"
                weight = 7
            [[languages.de.menu.main]]
                name = "Abrakadabra"
                url = "/manipulierbarkeit/"
                weight = 8
            [[languages.de.menu.main]]
                name = "Auf Spurensuche"
                url = "/frequenzgehalt/"
                weight = 9
            [[languages.de.menu.main]]
                name = "Auf die Grösse kommt's an"
                url = "/wellenlaenge/"
                weight = 10
            [[languages.de.menu.main]]
                name = "Wellen bewegen die Welt"
                url = "/gesellschaft/"
                weight = 11
            [[languages.de.menu.main]]
                name = "Zwei Seiten einer Medaille"
                url = "/risiken/"
                weight = 12

    [languages.en]
        title = "Waves, focusTerra"
        languageName = "en"
        weight = 2

        [languages.en.params]
        weiter = "Think Further"
        weiter_alt = "Think further icon for"
        fullscreen_image_alt = "Poster to the topic of"
        description = "The online exhibition accompanies the exhibition shown from 24 August 2021 to 5 March 2023 in focusTerra at ETH Zurich. There you can discover the waves on large illuminated illustrations and explore them yourself in many experiments. We look forward to your visit."

        [languages.en.menu]
            [[languages.en.menu.home]]
                name = "Home"
                url = "/"
                weight = 1
            [[languages.en.menu.intros]]
                name = "Dive In!"
                url = "/divein"
                weight = 1
            [[languages.en.menu.intros]]
                name = "Types of Waves"
                url = "/wavetypes"
                weight = 2
            [[languages.en.menu.intros]]
                name = "Wave Physics"
                url = "/wavephysics"
                weight = 3
            [[languages.en.menu.intros]]
                name = "Through Time with Waves"
                url = "/time"
                weight = 4
            [[languages.en.menu.main]]
                name = "I Spy with My Little Eye"
                url = "/receiver/"
                weight = 1
            [[languages.en.menu.main]]
                name = "Hello Echo"
                url = "/reflection/"
                weight = 2
            [[languages.en.menu.main]]
                name = "Ready-Steady-Go"
                url = "/speed/"
                weight = 3
            [[languages.en.menu.main]]
                name = "Energy in Focus"
                url = "/interference/"
                weight = 4
            [[languages.en.menu.main]]
                name = "Seek and You Will Find"
                url = "/localisation/"
                weight = 5
            [[languages.en.menu.main]]
                name = "Data Travels Around the world"
                url = "/communication/"
                weight = 6
            [[languages.en.menu.main]]
                name = "Travellers Have Stories to Tell"
                url = "/change/"
                weight = 7
            [[languages.en.menu.main]]
                name = "Abracadabra"
                url = "/manipulable/"
                weight = 8
            [[languages.en.menu.main]]
                name = "Hunting for Clues"
                url = "/frequencycontent/"
                weight = 9
            [[languages.en.menu.main]]
                name = "Size Matters"
                url = "/wavelength/"
                weight = 10
            [[languages.en.menu.main]]
                name = "Waves Move the World"
                url = "/society/"
                weight = 11
            [[languages.en.menu.main]]
                name = "Two Sides of the Same Coin"
                url = "/risks/"
                weight = 12